name: Publish to PyPI

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build + test deps
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
          # Install project (pulls runtime deps from pyproject)
          pip install -e .
      - name: Run tests
        run: pytest -q

  publish:
    name: Build & publish to PyPI
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # Set to true to skip pre-release checks (optional)
          # skip-existing: true
